module.exports.queries = {
  queryToCreateUser:
    "CREATE TABLE user (id INT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(50) NOT NULL,email VARCHAR(100) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);",

  queryToCreateProduct:
    "CREATE TABLE product (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL,price DECIMAL(10, 2) NOT NULL,description TEXT,category_id INT,availability ENUM('In Stock', 'Out of Stock') DEFAULT 'In Stock',qty INT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);",

  queryToCreateCart:
    "CREATE TABLE cart (id INT AUTO_INCREMENT PRIMARY KEY,product_id INT NOT NULL,user_id INT NOT NULL,order_id INT UNIQUE,qty INT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,total_price DECIMAL(10, 2) NOT NULL);",

  queryToCreateOrder:
    "CREATE TABLE MyOrder (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,total_price DECIMAL(10, 2) NOT NULL,payment_mode VARCHAR(50) NOT NULL,address VARCHAR(255) NOT NULL,status ENUM('progress', 'completed', 'uncompleted') NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);",
  queryToCreateCategory:
    "CREATE TABLE category (id INT AUTO_INCREMENT PRIMARY KEY,category_name VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);",
};
